language: python

sudo: required

dist: trusty

branches:
    only:
        - master

python:
    - "2.7"
    - "3.4"
    - "3.6"

addons:
    apt:
        packages:
            fuse

install:
    - pip install coveralls
    - pip install fusepy
    - pip install cryptography

script:
    - make test

after_success:
    - make coveralls
    - coveralls
