language: python

sudo: required

dist: trusty

branches:
    only:
        - master

python:
    - "2.7"

addons:
    apt:
        packages:
            fuse

install:
    - pip install fusepy
    - pip install pycrypto

script:
    - make test
