language: python

branches:
    only:
        - master

python:
    - "2.7"
    - "3.4"

addons:
    apt:
        packages:
            fuse

env:
    - CRYPTO_BACKEND=cryptography
    - CRYPTO_BACKEND=pycrypto

install:
    - pip install coveralls
    - pip install $CRYPTO_BACKEND
    - git clone https://github.com/fusepy/fusepy.git
    - cd fusepy
    - python setup.py install
    - cd ..

script:
    - make test

after_success:
    - make coveralls
    - coveralls
